### ISSUE TITLE
Implement the weather

### ISSUE THREAD

**Issue by pravee42** [pravee42/news-app#5]
Try to implement the feature which shows the weather below the profile pic
only the weather like [24.c] 

and upload the screen short too and add all the files including the screen short in folder named weather and add the component that shows weather when we call

- [ ] Create a component that shows weather

- [ ] Create the folder for the components add the folder inside the components folder and create a pull request

**Comment by pravee42** [comment]
any updated

**Comment by urtadolg** [comment]
Hi there, I would like to know more details about this project and this issue specifically. Maybe I could help you with this.

**Comment by pravee42** [comment]
> Hi there, I would like to know more details about this project and this issue specifically. Maybe I could help you with this.

Hi @urtadolg yes you can work on this project 
And thanks in advance 💖💖💖

**Comment by pravee42** [comment]
> Hi there, I would like to know more details about this project and this issue specifically. Maybe I could help you with this.

This is a news web application created using react js it shows news from **News api** which scraps data from different websites

- [ ] now I want to show the weather of the person location currently in below the avatar image (To see avatar login with google)
- [ ] And also if the person clicked the weather it will show forecasts also in the model view

This the Issue details you can try your best 
Best of luck

**Comment by pravee42** [comment]
Can build the application with `npm run build` and  make the PR again before that copy code some other place and make an `git pull` so that get my changes

**Comment by urtadolg** [comment]
Sure, I can do that. But before let me briefly explain:

That missing file _credentials contains a simple const variable API_KEY which receives the open weather key and this file is located on src/components/weather/hooks.

![apiKey](https://user-images.githubusercontent.com/89041463/146775652-dea6e091-fdf1-4d50-930e-f0dd38faf004.png)

My idea is to add this file in .gitignore so that you can replace it with your own API_KEY obtained from https://home.openweathermap.org/api_keys. Are you available to make a call or chat on LinkedIn / Discord for more details ?

**Comment by pravee42** [comment]
I can understand that you can add the file without the `API key` just delete the API ket and give only the double quotes inside the `_credientials.js`
My discord id : abipravi#1501

**Comment by pravee42** [comment]
I can itself add the file in the code 
but thanks for this much effort I will make an commit after the changes has been made

**Comment by urtadolg** [comment]
> I can understand that you can add the file without the `API key` just delete the API ket and give only the double quotes inside the `_credientials.js` My discord id : abipravi#1501

Done that, You only need now to paste your own key

**Comment by pravee42** [comment]
Done merged the PR for more let us char on discord as you said I have pasted my ID above
